language: ruby
addons:
  apt:
    packages:
      - libgmp-dev
rvm:
  - 2.2.4
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_script:
  - rails new example_app
  - echo "gem 'render_component', path: '..'" >> example_app/Gemfile
script: "bundle exec rake test"
